### ISSUE TITLE
Publicar en Shinyapp.io

### ISSUE THREAD

**Issue by paocorrales** [INTA-Suelos/sisintar-web#2]
- Crear una cuenta sisintar en Shinyapps --> @angelini75  / @yabellini 
- Subir la app con la base completa para que quede de prueba (csv individuales por perfil) --> @eliocamp / @paocorrales

**Comment by yabellini** [comment]
Correo creado: sisintar.app@gmail.com
Cuenta de shinny: sisinta

Luego paso las contraseñas.  No puedo agregar más personas al equipo de administración de la cuenta porque necesito el pro para poder hacerlo.

**Comment by eliocamp** [comment]
Ya astá público acá: 

https://sisinta.shinyapps.io/sisintar-web/
