### ISSUE TITLE
interpolacion

### ISSUE THREAD

**Issue by angelini75** [INTA-Suelos/sisintar-web#5]
@eliocamp 
La interpolación debería hacerse en base a rangos definidos por el usuario, ya que generlamente se piden intervalos de diferentes profundidades. El más usual es 0-5, 5-15, 15-30, 30-60, 60-100, 100-200. A esos se le llaman horizontes estándares (creo que no los introducimos antes). Entonces idealmente deberían tenerse como opción de interpolacion uno o mas de estos horizontes, y adicionalmente el usuario podría pedir esos y/o un espesor determinado, por ejemplo `limite_superior=5, limite_inferior=20`.

**Comment by paocorrales** [comment]
El usuario tendría la posibilidad de elegir: 

* intervalos pre-establecidos: 0-5, 5-15, 15-30, 30-60, 60-100, 100-200 (1 o varios)
* un intervalo específico pudiendo ingresar el límite superior y el límite inferior. En principio si necesita más de un intervalo específico, tendría que exportar varias veces.
